### PR TITLE
Fix model blank for admin UI

### PR DESCRIPTION
**Pull request by imsickofmaps**

### CODE REVIEW

**Comment by imsickofmaps** [comment]
@smn  review please

**Comment by smn** [comment]
@imsickofmaps thanks, what does this fix though?

**Comment by imsickofmaps** [comment]
@smn when you edit a `Celery cron definition` FK in the `/admin/scheduler/schedule/<schedule uuid>/change/` you can't save it currently. If you save it, it should reload the schedule without requiring bouncing the container for beat.

**Comment by smn** [comment]
:+1:

**Pull request merged**
