### PR TITLE
Improved admin usage

### PR DESCRIPTION
**Pull request by gsvr**

### CODE REVIEW

**Comment by gsvr** [comment]
@rudigiesler @jpaidoussi Please review.

**Comment by bruskiza** [comment]
@rudigiesler @jpaidoussi poink ^^^

**Review by jpaidoussi — APPROVED** [review]

**Comment by gsvr** [comment]
@jpaidoussi @smn Review is still required.

**Comment by jpaidoussi** [comment]
Wasn't it approved 28 days ago?

**Comment by gsvr** [comment]
Oh, missed it since no :+1:

**Pull request merged**
